import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/seo";

/**
 * robots.txt (generated by Next).
 *
 * Everything public is crawlable. The transactional and private surfaces are
 * disallowed: `/book` and `/trip` are per-booking pages already marked
 * `noindex`, and `/api` is the JSON layer, not content. The sitemap points
 * crawlers at the pages that should rank.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: ["/api/", "/book/", "/trip/"],
    },
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
