import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/seo";
import { getAllStays } from "@/services/stay.service";
import { getAllExperiences } from "@/services/experience.service";
import { getAllGuides } from "@/services/guide.service";

/**
 * sitemap.xml (generated by Next).
 *
 * The static marketing/legal routes, plus every published stay, experience and
 * guide pulled from the service layer. If a database read fails, it degrades to
 * the static routes rather than 500-ing the sitemap — a partial sitemap beats
 * none. The transactional `/book` and `/trip` pages are deliberately absent
 * (they're `noindex` and disallowed in robots.txt).
 */
export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const staticRoutes: MetadataRoute.Sitemap = [
    { url: `${SITE_URL}/`, changeFrequency: "weekly", priority: 1 },
    { url: `${SITE_URL}/explore`, changeFrequency: "daily", priority: 0.9 },
    {
      url: `${SITE_URL}/experiences`,
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/travel-guide`,
      changeFrequency: "weekly",
      priority: 0.7,
    },
    { url: `${SITE_URL}/about`, changeFrequency: "monthly", priority: 0.5 },
    { url: `${SITE_URL}/contact`, changeFrequency: "monthly", priority: 0.5 },
    {
      url: `${SITE_URL}/become-a-host`,
      changeFrequency: "monthly",
      priority: 0.5,
    },
    { url: `${SITE_URL}/privacy`, changeFrequency: "yearly", priority: 0.2 },
    { url: `${SITE_URL}/terms`, changeFrequency: "yearly", priority: 0.2 },
  ];

  try {
    const [stays, experiences, guides] = await Promise.all([
      getAllStays(),
      getAllExperiences(),
      getAllGuides(),
    ]);

    const stayRoutes: MetadataRoute.Sitemap = stays.map((stay) => ({
      url: `${SITE_URL}/stays/${stay.slug}`,
      lastModified: stay.createdAt,
      changeFrequency: "weekly",
      priority: 0.8,
    }));

    const experienceRoutes: MetadataRoute.Sitemap = experiences.map((exp) => ({
      url: `${SITE_URL}/experiences/${exp.slug}`,
      changeFrequency: "monthly",
      priority: 0.6,
    }));

    const guideRoutes: MetadataRoute.Sitemap = guides.map((guide) => ({
      url: `${SITE_URL}/travel-guide/${guide.slug}`,
      lastModified: guide.publishedAt ?? undefined,
      changeFrequency: "monthly",
      priority: 0.6,
    }));

    return [
      ...staticRoutes,
      ...stayRoutes,
      ...experienceRoutes,
      ...guideRoutes,
    ];
  } catch {
    return staticRoutes;
  }
}
